Layout/IndentationWidth:
  Width: 4
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
AllCops:
  TargetRubyVersion: 2.3.3
Style/DocumentationMethod:
  RequireForNonPublicMethods: false
Style/GlobalVars:
  AllowedVariables: ['$client', '$collection_urls', '$command_urls']
Metrics/MethodLength:
  Max: 16
