Layout/IndentationWidth:
  Width: 4
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
AllCops:
  TargetRubyVersion: 2.3.3
Style/DocumentationMethod:
  RequireForNonPublicMethods: false
#Style/Documentation: false
Style/GlobalVars:
  AllowedVariables: ['$client', '$collection_urls', '$command_urls']
Style/GuardClause:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Metrics/MethodLength:
  Max: 16
Metrics/AbcSize:
  Enabled: false
